---
- name: Download latest Obsidian AppImage
  hosts: localhost
  tasks:
    - name: Get the latest release information
      ansible.builtin.uri:
        url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
        return_content: yes
      register: release_info

    - name: Extract AppImage URL
      set_fact:
        appimage_url: "{{ release_info.json.assets | selectattr('name', 'search', 'arm64.AppImage') | map(attribute='browser_download_url') | first }}"

    - name: Download the latest Obsidian AppImage
      ansible.builtin.get_url:
        url: "{{ appimage_url }}"
        dest: "/home/mrinal/Obsidian.AppImage"
        mode: "0755"
