# Step 1: Install DNF Groups

- name: Install core, multimedia, sound-and-video DNF groups
  dnf:
    name:
      - "@core"
      - "@multimedia"
      - "@sound-and-video"
    state: present

# Step 2: Install RPM Fusion Repositories

- name: Ensure RPM Fusion Free and Non Free repositories are installed
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    disable_gpg_check: true
    state: present

- name: Upgrade core group
  command:
    cmd: dnf group upgrade -y core

- name: Upgrade all
  command:
    cmd: dnf --refresh upgrade --allowerasing --best

# Step 3: Swap ffmpeg-free with ffmpeg

- name: Swap ffmpeg-free with ffmpeg
  command:
    cmd: dnf swap -y ffmpeg-free ffmpeg --allowerasing

# Step 4: Upgrade DNF Groups

- name: Upgrade multimedia group without weak dependencies
  command:
    cmd: dnf group upgrade -y multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

- name: Upgrade sound-and-video group
  command:
    cmd: dnf group upgrade -y sound-and-video

- name: Upgrade all
  command:
    cmd: dnf --refresh upgrade --allowerasing --best

# Step 5: Install browsers
- name: Install chromium
  dnf:
    name:
      - chromium-browser
    state: present

- name: Widevine setup to enable DRM
  shell: echo -e "\n\n" | /usr/bin/widevine-installer
  ignore-errors: true
