# Step 1: Install DNF Groups

- name: Install multimedia DNF group
  dnf:
    name: "@multimedia"
    state: present

- name: Install sound-and-video DNF group
  dnf:
    name: "@sound-and-video"
    state: present

- name: Install core DNF group
  dnf:
    name: "@core"
    state: present

# Step 2: Install RPM Fusion Repositories

- name: Ensure RPM Fusion Free repository is installed
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present

- name: Ensure RPM Fusion Non-Free repository is installed
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present

# Step 3: Swap ffmpeg-free with ffmpeg

- name: Swap ffmpeg-free with ffmpeg
  command:
    cmd: dnf swap -y ffmpeg-free ffmpeg --allowerasing

# Step 4: Upgrade DNF Groups

- name: Upgrade multimedia group without weak dependencies
  command:
    cmd: dnf group upgrade -y multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

- name: Upgrade sound-and-video group
  command:
    cmd: dnf group upgrade -y sound-and-video

- name: Upgrade core group
  command:
    cmd: dnf group upgrade -y core
