- name: Set up Fedora environment
  hosts: localhost
  become: true
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  roles:
    - { role: multimedia, tags: install }
    - { role: packages, tags: install }
    - { role: gnome, tags: install }
    - role: github
      tags: config
      become_user: "{{ ansible_user }}"
    - role: dotfiles
      tags: config
      become_user: "{{ ansible_user }}"
    - role: fonts
      tags: config
      become_user: "{{ ansible_user }}"
