# roles/github/tasks/main.yml
- name: Authenticate with GitHub using a token
  shell: |
    echo "{{ github_token }}" | gh auth login --with-token
  no_log: true # Hide sensitive output

  # roles/github/tasks/main.yml
- name: Ensure ~/.gitconfig is deployed
  copy:
    src: files/gitconfig
    dest: $HOME/.gitconfig
    mode: "0644"
