# roles/dotfiles/tasks/main.yml
# Ensure that nested directories exist
- name: Ensure nested directories exist
  file:
    path: $HOME/.config/environment.d
    state: directory
    mode: "0755"

- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    update: yes

- name: Apply dotfiles using stow
  shell: stow .
  args:
    chdir: "{{ dotfiles_dir }}"

- name: Chromium flags
  copy:
    src: files/chromium-flags.conf
    dest: $HOME/.config/environment.d/chromium.conf
    mode: "0600"
