# roles/bluetooth/tasks/main.yml
- name: Ensure Bluetooth service is running
  service:
    name: bluetooth
    state: started
    enabled: yes

- name: Pair Bluetooth devices
  shell: |
    bluetoothctl pair {{ item.mac }} || true
    bluetoothctl trust {{ item.mac }} || true
    bluetoothctl connect {{ item.mac }} || true
  loop: "{{ bluetooth_devices }}"
  ignore_errors: yes
  when: item.mac is defined
