---
- block:
    - name: Install required packages
      dnf:
        name: "{{ packages }}"
        state: present
  become: true
  name: Packages

- block:
    - name: Enable COPR repositories dynamically
      ansible.builtin.command:
        cmd: dnf copr enable -y {{ item.repo }} fedora-{{ ansible_distribution_version }}-{{ ansible_architecture }}
      loop: "{{ coprs }}"

    - name: Install packages from COPR dynamically
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: present
      loop: "{{ coprs }}"
  become: true
  tags: copr
  name: Copr

- block:
    - name: Replace VIM with NEOVIM
      dnf:
        name:
          - neovim
        state: present

    # Create a custom nvim-clean wrapper
    - name: Create nvim-clean wrapper script
      copy:
        dest: /usr/local/bin/nvim-clean
        content: |
          #!/bin/sh
          exec nvim --clean "$@"
        mode: "0755"

    - name: Set nvim-clean as alternative for vim
      alternatives:
        name: vim
        link: /usr/bin/vim
        path: /usr/local/bin/nvim-clean
        priority: 50
  become: true
  name: NEOVIM
