# roles/network/tasks/main.yml
- name: Ensure NetworkManager Directory exists
  file:
    path: /etc/NetworkManager/system-connections
    state: directory
    mode: "0755"

- name: Deploy Wi-Fi configuration
  template:
    src: files/Yara.nmconnection
    dest: /etc/NetworkManager/system-connections/Yara.nmconnection
    mode: "0600"
  notify: Restart NetworkManager

# Handler to restart NetworkManager
- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
