- name: Install required packages
  dnf:
    name:
      - gnome-tweaks
      - gnome-extensions-app
      - git
    state: present
- name: Apply GNOME settings
  copy:
    src: files/gnome-settings.dconf
    dest: /tmp/gnome-settings.dconf
  become: true
  become_user: "{{ ansible_user }}"

- name: Load GNOME settings using dconf
  shell: dconf load -f / < /tmp/gnome-settings.dconf
  ignore_errors: true
  become: true
  become_user: "{{ ansible_user }}"

- name: update dconf systemwide
  shell: dconf update

- name: Install system shell extensions packages
  dnf:
    name: "{{ shell_extensions }}"
    state: present
