- name: Update kernel parameters
  command: grubby --args="{{ kernel_args }} apple_dcp.show_notch=1 slub_debug=-" --update-kernel=ALL

- name: Widevine setup
  shell: echo -e "\n\n" | /usr/bin/widevine-installer
