---
- block:
    - name: Install required packages
      dnf:
        name: "{{ packages }}"
        state: present
  become: true
  name: Packages

- block:
    - name: Enable COPR repositories dynamically
      ansible.builtin.command:
        cmd: dnf copr enable -y {{ item.repo }} fedora-{{ ansible_distribution_version }}-{{ ansible_architecture }}
      loop: "{{ coprs }}"

    - name: Install packages from COPR dynamically
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: present
      loop: "{{ coprs }}"
  become: true
  tags: copr
  name: Copr

- block:
    - name: Replace VIM with NEOVIM
      dnf:
        name:
          - neovim
        state: present

    # Create a custom nvim-clean wrapper
    - name: Create nvim-clean wrapper script
      copy:
        dest: /usr/local/bin/nvim-clean
        content: |
          #!/bin/sh
          exec nvim --clean "$@"
        mode: "0755"

    - name: Set nvim-clean as alternative for vim
      alternatives:
        name: vim
        link: /usr/bin/vim
        path: /usr/local/bin/nvim-clean
        priority: 50
  become: true
  name: NEOVIM

- block:
    # 1Password Installation
    - name: Ensure 1Password directory exists
      file:
        path: "{{ onepassword_dir }}"
        state: directory
        mode: "0755"

    - name: Extract 1Password
      unarchive:
        src: "{{ onepassword_url }}"
        dest: "{{ onepassword_dir }}"
        extra_opts: ["--strip-components=1", "--show-stored-names"]
        remote_src: yes

    - name: Run 1Password post-install script
      command: /opt/1Password/after-install.sh
  become: true
  tags: 1password
  name: 1PASSWORD
