# vars/main.yml
---
rpmfusion_free_url: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
rpmfusion_nonfree_url: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
onepassword_url: "https://downloads.1password.com/linux/tar/beta/aarch64/1password-latest.tar.gz"
onepassword_dir: "/opt/1Password"
kernel_args: "apple_dcp.show_notch=1 slub_debug=-"
packages:
  - unzip
  - tmux
  - tmux-powerline
  - tmux-top
  - podman
  - toolbox
  - gh
  - stow
  - git
  - qemu-user-static-x86
  - htop
  - flatpak
