---
- block:
    # Step 1: Install RPM Fusion Repositories
    - name: Ensure RPM Fusion Free and Non Free repositories are installed
      dnf:
        name:
          - "{{ rpmfusion_free_url }}"
          - "{{ rpmfusion_nonfree_url }}"
        disable_gpg_check: true
        state: present

    # Step 2: Install DNF Groups
    - name: Install core, multimedia, sound-and-video DNF groups
      dnf:
        name:
          - "@core"
          - "@multimedia"
          - "@sound-and-video"
        state: latest

    # Step 3: Swap ffmpeg-free with ffmpeg
    - name: Swap ffmpeg-free with ffmpeg
      command: dnf swap ffmpeg-free ffmpeg --allowerasing -y
      ignore_errors: true

    # Step 4: Upgrade DNF Groups
    - name: Upgrade multimedia group without weak dependencies
      dnf:
        name: "@multimedia"
        state: latest
        disable_excludes: PackageKit-gstreamer-plugin

    - name: Upgrade sound-and-video group
      dnf:
        name: "@sound-and-video"
        state: latest
  become: true
  name: Multimedia
  vars:
    rpmfusion_free_url: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    rpmfusion_nonfree_url: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
