# roles/fonts/tasks/main.yml
- name: Ensure fonts directory exists
  file:
    path: $HOME/.local/share/fonts
    state: directory
    mode: "0755"

- name: Download and extract fonts
  block:
    - name: Download {{ item.name }} font
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.name }}.tar.xz"
        mode: "0644"
      register: font_download
      loop: "{{ fonts }}" # Corrected loop application

    - name: Extract {{ item.name }} font
      unarchive:
        src: "/tmp/{{ item.name }}.tar.xz"
        dest: "$HOME/.local/share/fonts"
        remote_src: yes
      when: font_download is succeeded
      loop: "{{ fonts }}" # Corrected loop application

  rescue:
    - name: Handle errors if download or extraction fails
      debug:
        msg: "Failed to download or extract fonts."
